### ISSUE TITLE
Laravel 6 issue

### ISSUE THREAD

**Issue by Jon78** [nikaia/nova-rating-field#8]
This package breaks in Laravel 6. Issue has been fixed in #3 but the version number has not been changed. Quick workaround is to require this specific commit (dev-master#c0661d9) in composer.json.

**Comment by pelmered** [comment]
Can you please tag a new version @nbourguig ?

**Comment by nbourguig** [comment]
Sorry for the delay.

https://github.com/nikaia/nova-rating-field/releases/tag/1.0.1
